# Generated by Django 5.1.7 on 2025-06-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='descricao',
            new_name='observacao',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='composto',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='meia_vida',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='frequencia',
            field=models.CharField(choices=[('Diário', 'Diário'), ('Semanal', 'Semanal')], default='Diário', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosagem',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(),
        ),
    ]
