# Generated by Django 5.1.7 on 2025-06-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_descricao_medicamento_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='dosagem',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosagem_unidade',
            field=models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('ml', 'ml'), ('gotas', 'gotas'), ('comprimido(s)', 'comprimido(s)'), ('cápsula(s)', 'cápsula(s)')], default='mg', max_length=20),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosagem_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
