# Generated by Django 5.1.7 on 2025-06-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_medicamento_dosagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
